name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs#coreutils' -- --coreutils-prog=ginstall -p "./result" '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
