version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/test-suite/languages/rust"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "/test-suite/compose"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
