name: test-suite

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        package:
        - test-suite-rust-numbers-wasm32-unknown-unknown
        - test-suite-rust-numbers-wasm32-wasi
        - test-suite-rust-trivial-wasm32-unknown-unknown
        - test-suite-rust-trivial-wasm32-wasi

    name: ${{ matrix.package }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: ./.github/actions/build-nix
      with:
        package: ${{ matrix.package }}

  cargo:
    strategy:
      matrix:
        check:
        - test-suite-compose-audit
        - test-suite-compose-fmt
        - test-suite-compose-clippy
        - test-suite-compose-nextest
        - test-suite-rust-audit
        - test-suite-rust-fmt

    name: cargo ${{ matrix.check }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}
